version: "3.9"

services:
  web:
    build: .
    container_name: flask_api
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx_app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
